version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: alessandrror/flask_crud_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgresql:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSGRES_PASSWORD=postgres
      - POSGRES_USER=postgres
      - POSGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
